# Generated by Django 5.2.15 on 2026-06-30 02:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("label", models.CharField(max_length=180, verbose_name="etiqueta")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadatos"
                    ),
                ),
            ],
            options={
                "verbose_name": "evidencia",
                "verbose_name_plural": "evidencias",
                "ordering": ("event__occurred_at", "label"),
            },
        ),
        migrations.CreateModel(
            name="TraceEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ocurrió en"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=120, verbose_name="tipo de evento"),
                ),
                (
                    "object_label",
                    models.CharField(max_length=220, verbose_name="objeto"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="datos"),
                ),
            ],
            options={
                "verbose_name": "evento de trazabilidad",
                "verbose_name_plural": "eventos de trazabilidad",
                "ordering": ("-occurred_at",),
            },
        ),
    ]
