"""Navigation metadata for the base layout."""

NAVIGATION_ITEMS = [
    {"label": "Dashboard", "url_name": "dashboard", "icon": "bi-speedometer2"},
    {"label": "Clínicas", "url_name": "clinics", "icon": "bi-hospital"},
    {"label": "Consultorios", "url_name": "rooms", "icon": "bi-door-open"},
    {
        "label": "Especialidades",
        "url_name": "specialties",
        "icon": "bi-clipboard2-pulse",
    },
    {"label": "Equipamiento", "url_name": "equipment", "icon": "bi-tools"},
    {"label": "Propietarios", "url_name": "owners", "icon": "bi-person-badge"},
    {
        "label": "Médicos Arrendatarios",
        "url_name": "tenant_doctors",
        "icon": "bi-person-vcard",
    },
    {"label": "Disponibilidad", "url_name": "availability", "icon": "bi-calendar-week"},
    {"label": "Calendario", "url_name": "calendar_week", "icon": "bi-calendar3"},
    {"label": "Vista rápida", "url_name": "calendar_quick", "icon": "bi-grid-3x3-gap"},
    {"label": "Tarifas", "url_name": "rates", "icon": "bi-cash-coin"},
    {"label": "Reservaciones", "url_name": "reservations", "icon": "bi-calendar-check"},
    {"label": "Estados de Cuenta", "url_name": "statements", "icon": "bi-receipt"},
    {"label": "Pagos", "url_name": "payments", "icon": "bi-credit-card"},
    {"label": "Liquidaciones", "url_name": "settlements", "icon": "bi-bank"},
    {"label": "Documentos", "url_name": "documents", "icon": "bi-file-earmark-pdf"},
    {"label": "Accesos", "url_name": "access_credentials", "icon": "bi-key"},
    {"label": "Timeline", "url_name": "timeline", "icon": "bi-diagram-3"},
    {"label": "Reportes", "url_name": "reports", "icon": "bi-bar-chart"},
    {"label": "Administración", "url_name": "administration", "icon": "bi-gear"},
]

PAGE_TITLES = {
    "clinics": "Clínicas",
    "rooms": "Consultorios",
    "specialties": "Especialidades",
    "equipment": "Equipamiento",
    "owners": "Propietarios",
    "tenant_doctors": "Médicos Arrendatarios",
    "availability": "Disponibilidad",
    "calendar_week": "Calendario",
    "calendar_quick": "Vista rápida",
    "rates": "Tarifas",
    "reservations": "Reservaciones",
    "statements": "Estados de Cuenta",
    "payments": "Pagos",
    "settlements": "Liquidaciones",
    "documents": "Documentos",
    "access_credentials": "Accesos",
    "timeline": "Timeline",
    "reports": "Reportes",
    "administration": "Administración",
}
