# Generated by Django 5.2.15 on 2026-09-30 20:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0006_consultingroom_campus_consultingroom_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="versión"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha inicio de vigencia",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha fin de vigencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("name", models.CharField(max_length=160, verbose_name="nombre")),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellation_policies",
                        to="catalog.clinic",
                        verbose_name="clínica",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancellation_policies",
                        to="catalog.consultingroom",
                        verbose_name="consultorio específico",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "política de cancelación",
                "verbose_name_plural": "políticas de cancelación",
                "ordering": ("clinic__name", "room__name", "-start_date", "-version"),
            },
        ),
        migrations.CreateModel(
            name="CancellationPenaltyRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "days_before",
                    models.PositiveSmallIntegerField(
                        verbose_name="días naturales antes"
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        verbose_name="porcentaje de penalización",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="penalty_rules",
                        to="billing.cancellationpolicy",
                        verbose_name="política",
                    ),
                ),
            ],
            options={
                "verbose_name": "regla de penalización por cancelación",
                "verbose_name_plural": "reglas de penalización por cancelación",
                "ordering": ("policy", "days_before"),
            },
        ),
        migrations.CreateModel(
            name="OwnerCommissionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="versión"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha inicio de vigencia",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha fin de vigencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        verbose_name="porcentaje de comisión",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_rules",
                        to="catalog.ownerprofile",
                        verbose_name="propietario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "regla de comisión del propietario",
                "verbose_name_plural": "reglas de comisión de propietarios",
                "ordering": ("owner__display_name", "-start_date", "-version"),
            },
        ),
        migrations.CreateModel(
            name="OwnerPayoutSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="versión"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha inicio de vigencia",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha fin de vigencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Semanal"),
                            ("biweekly", "Quincenal"),
                            ("monthly", "Mensual"),
                        ],
                        max_length=12,
                        verbose_name="frecuencia de pago",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_schedules",
                        to="catalog.ownerprofile",
                        verbose_name="propietario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "frecuencia de pago al propietario",
                "verbose_name_plural": "frecuencias de pago a propietarios",
                "ordering": ("owner__display_name", "-start_date", "-version"),
            },
        ),
        migrations.CreateModel(
            name="OwnerSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="versión"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha inicio de vigencia",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha fin de vigencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Mensual"), ("annual", "Anual")],
                        default="monthly",
                        max_length=12,
                        verbose_name="periodicidad",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="importe"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="moneda"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_rules",
                        to="catalog.ownerprofile",
                        verbose_name="propietario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "suscripción de propietario",
                "verbose_name_plural": "suscripciones de propietarios",
                "ordering": ("owner__display_name", "-start_date", "-version"),
            },
        ),
        migrations.CreateModel(
            name="RoomFixedFeeRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="versión"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha inicio de vigencia",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha fin de vigencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("maintenance", "Mantenimiento"),
                            ("internet", "Internet"),
                            ("electricity", "Electricidad"),
                            ("cleaning", "Limpieza"),
                            ("receptionist", "Recepcionista"),
                            ("miscellaneous", "Diversos"),
                        ],
                        max_length=24,
                        verbose_name="tipo de cuota",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="importe"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="moneda"
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("direct", "Pago directo del propietario"),
                            ("auto_deduct", "Descuento automático al cierre"),
                        ],
                        default="direct",
                        max_length=16,
                        verbose_name="forma de pago",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_fee_rules",
                        to="catalog.consultingroom",
                        verbose_name="consultorio",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "regla de cuota fija",
                "verbose_name_plural": "reglas de cuotas fijas",
                "ordering": (
                    "room__clinic__name",
                    "room__name",
                    "fee_type",
                    "-start_date",
                ),
            },
        ),
        migrations.CreateModel(
            name="RoomMonthlyFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="versión"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha inicio de vigencia",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha fin de vigencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("maintenance", "Mantenimiento"),
                            ("internet", "Internet"),
                            ("electricity", "Electricidad"),
                            ("cleaning", "Limpieza"),
                            ("receptionist", "Recepcionista"),
                            ("miscellaneous", "Diversos"),
                        ],
                        max_length=24,
                        verbose_name="tipo de cuota",
                    ),
                ),
                ("billing_month", models.DateField(verbose_name="mes de cobro")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="importe"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="moneda"
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("direct", "Pago directo del propietario"),
                            ("auto_deduct", "Descuento automático al cierre"),
                        ],
                        default="direct",
                        max_length=16,
                        verbose_name="forma de pago",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_fees",
                        to="catalog.consultingroom",
                        verbose_name="consultorio",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "cuota mensual variable",
                "verbose_name_plural": "cuotas mensuales variables",
                "ordering": (
                    "-billing_month",
                    "room__clinic__name",
                    "room__name",
                    "fee_type",
                ),
            },
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, editable=False, verbose_name="versión"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha inicio de vigencia",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha fin de vigencia"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Mensual"), ("annual", "Anual")],
                        default="monthly",
                        max_length=12,
                        verbose_name="periodicidad",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="importe"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="moneda"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_rules",
                        to="catalog.tenantdoctorprofile",
                        verbose_name="médico arrendatario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "suscripción de médico arrendatario",
                "verbose_name_plural": "suscripciones de médicos arrendatarios",
                "ordering": ("tenant_doctor__display_name", "-start_date", "-version"),
            },
        ),
        migrations.AddConstraint(
            model_name="cancellationpolicy",
            constraint=models.UniqueConstraint(
                fields=("clinic", "room", "version"),
                name="billing_cancellation_policy_unique_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="cancellationpenaltyrule",
            constraint=models.UniqueConstraint(
                fields=("policy", "days_before"),
                name="billing_cancellation_penalty_unique_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="cancellationpenaltyrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("percentage__gte", 0), ("percentage__lte", 100)),
                name="billing_cancellation_penalty_percentage_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownercommissionrule",
            constraint=models.UniqueConstraint(
                fields=("owner", "version"),
                name="billing_owner_commission_unique_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownercommissionrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("percentage__gte", 0), ("percentage__lte", 100)),
                name="billing_owner_commission_percentage_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerpayoutschedule",
            constraint=models.UniqueConstraint(
                fields=("owner", "version"), name="billing_owner_payout_unique_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownersubscription",
            constraint=models.UniqueConstraint(
                fields=("owner", "version"),
                name="billing_owner_subscription_unique_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownersubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="billing_owner_subscription_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomfixedfeerule",
            constraint=models.UniqueConstraint(
                fields=("room", "fee_type", "version"),
                name="billing_room_fixed_fee_unique_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomfixedfeerule",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="billing_room_fixed_fee_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="roommonthlyfee",
            constraint=models.UniqueConstraint(
                fields=("room", "fee_type", "billing_month", "version"),
                name="billing_room_monthly_fee_unique_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="roommonthlyfee",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="billing_room_monthly_fee_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantsubscription",
            constraint=models.UniqueConstraint(
                fields=("tenant_doctor", "version"),
                name="billing_tenant_subscription_unique_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="billing_tenant_subscription_nonnegative",
            ),
        ),
    ]
