# Generated by Django 5.2.15 on 2026-06-30 02:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="importe"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=24,
                        verbose_name="estado",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="pagado en"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="referencia"
                    ),
                ),
            ],
            options={
                "verbose_name": "pago",
                "verbose_name_plural": "pagos",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RateRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=160, verbose_name="nombre")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="importe"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="moneda"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="predeterminada"),
                ),
            ],
            options={
                "verbose_name": "regla tarifaria",
                "verbose_name_plural": "reglas tarifarias",
                "ordering": ("room__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "folio",
                    models.CharField(max_length=80, unique=True, verbose_name="folio"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("issued", "Emitido"),
                            ("paid", "Pagado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="estado",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="total"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="moneda"
                    ),
                ),
            ],
            options={
                "verbose_name": "estado de cuenta",
                "verbose_name_plural": "estados de cuenta",
                "ordering": ("folio",),
            },
        ),
    ]
