# Generated by Django 5.2.15 on 2026-06-30 04:52

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="raterule",
            options={
                "ordering": ("room__name", "-priority", "start_time"),
                "verbose_name": "regla tarifaria",
                "verbose_name_plural": "reglas tarifarias",
            },
        ),
        migrations.RemoveField(
            model_name="raterule",
            name="is_default",
        ),
        migrations.AddField(
            model_name="raterule",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="fecha fin"),
        ),
        migrations.AddField(
            model_name="raterule",
            name="end_time",
            field=models.TimeField(
                default=datetime.time(9, 0), verbose_name="hora fin"
            ),
        ),
        migrations.AddField(
            model_name="raterule",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notas"),
        ),
        migrations.AddField(
            model_name="raterule",
            name="price_type",
            field=models.CharField(
                choices=[("por_hora", "Por hora"), ("por_bloque", "Por bloque")],
                default="por_hora",
                max_length=16,
                verbose_name="tipo de precio",
            ),
        ),
        migrations.AddField(
            model_name="raterule",
            name="priority",
            field=models.PositiveIntegerField(default=1, verbose_name="prioridad"),
        ),
        migrations.AddField(
            model_name="raterule",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="fecha inicio"
            ),
        ),
        migrations.AddField(
            model_name="raterule",
            name="start_time",
            field=models.TimeField(
                default=datetime.time(8, 0), verbose_name="hora inicio"
            ),
        ),
        migrations.AddField(
            model_name="raterule",
            name="weekdays",
            field=models.JSONField(default=list, verbose_name="días de semana"),
        ),
    ]
