# Generated by Django 5.2.15 on 2026-06-30 05:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_raterule_options_remove_raterule_is_default_and_more"),
        (
            "scheduling",
            "0003_alter_reservation_options_remove_reservation_end_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statement",
            options={
                "ordering": (
                    "reservation__date",
                    "reservation__start_time",
                    "-version",
                ),
                "verbose_name": "estado de cuenta",
                "verbose_name_plural": "estados de cuenta",
            },
        ),
        migrations.RemoveField(
            model_name="statement",
            name="folio",
        ),
        migrations.RemoveField(
            model_name="statement",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="statement",
            name="applied_rate_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statements",
                to="finance.raterule",
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="calculation_explanation",
            field=models.TextField(blank=True, verbose_name="explicación de cálculo"),
        ),
        migrations.AddField(
            model_name="statement",
            name="calculation_hash",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="hash de cálculo"
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="commission_taxes",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="impuestos comisión",
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="discounts",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="descuentos"
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="duration_hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="duración horas"
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="generated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="generado en"
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="owner_net",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="neto propietario",
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="platform_commission",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="comisión plataforma",
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="subtotal"
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="taxes",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="impuestos"
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="total_doctor",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="total médico"
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="versión"),
        ),
        migrations.AlterField(
            model_name="statement",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statements",
                to="scheduling.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="status",
            field=models.CharField(
                choices=[
                    ("vigente", "Vigente"),
                    ("reemplazado", "Reemplazado"),
                    ("cancelado", "Cancelado"),
                ],
                default="vigente",
                max_length=24,
                verbose_name="estado",
            ),
        ),
        migrations.AddConstraint(
            model_name="statement",
            constraint=models.UniqueConstraint(
                fields=("reservation", "version"),
                name="finance_statement_unique_reservation_version",
            ),
        ),
    ]
