# Generated by Django 5.2.15 on 2026-06-30 06:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_equipment_options_and_more"),
        ("finance", "0005_payment_manual_fields"),
        (
            "scheduling",
            "0003_alter_reservation_options_remove_reservation_end_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="moneda"
                    ),
                ),
                (
                    "reservation_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="subtotal reservación",
                    ),
                ),
                (
                    "platform_commission",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="comisión plataforma",
                    ),
                ),
                (
                    "commission_taxes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="impuestos comisión",
                    ),
                ),
                (
                    "owner_net",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="neto propietario"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("calculada", "Calculada"),
                            ("pagada", "Pagada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="calculada",
                        max_length=24,
                        verbose_name="estado",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="referencia de pago"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de pago"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "generated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="generada en"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="pagada en"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="catalog.ownerprofile",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="scheduling.reservation",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="catalog.consultingroom",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="finance.statement",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "liquidación",
                "verbose_name_plural": "liquidaciones",
                "ordering": ("-generated_at",),
            },
        ),
    ]
