# Generated by Django 5.2.15 on 2026-08-11 22:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_statement_tariffs(apps, schema_editor):
    statement = apps.get_model("finance", "Statement")
    statement.objects.update(
        tariff_total=F("subtotal"),
        tariff_final=F("total_doctor"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_consultingroom_campus_consultingroom_number_and_more"),
        ("finance", "0006_settlement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="room_discount_percentage",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=4,
                verbose_name="descuento consultorio %",
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="tariff_final",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="tarifa final"
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="tariff_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="tarifa total"
            ),
        ),
        migrations.AddField(
            model_name="statement",
            name="tenant_discount_percentage",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=4,
                verbose_name="descuento médico arrendatario %",
            ),
        ),
        migrations.RunPython(
            backfill_statement_tariffs,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="RoomRateDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        verbose_name="porcentaje de descuento",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="fecha inicio de vigencia"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha fin de vigencia"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rate_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="room_discounts",
                        to="finance.raterule",
                        verbose_name="regla tarifaria",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rate_discounts",
                        to="catalog.consultingroom",
                        verbose_name="consultorio",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "descuento por consultorio",
                "verbose_name_plural": "descuentos por consultorio",
                "ordering": (
                    "room__clinic__name",
                    "room__name",
                    "-start_date",
                    "-created_at",
                ),
            },
        ),
        migrations.AddField(
            model_name="statement",
            name="applied_room_discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statements",
                to="finance.roomratediscount",
            ),
        ),
        migrations.CreateModel(
            name="TenantDoctorDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        verbose_name="porcentaje de descuento",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="fecha inicio de vigencia"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha fin de vigencia"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discounts",
                        to="catalog.tenantdoctorprofile",
                        verbose_name="médico arrendatario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "descuento por médico arrendatario",
                "verbose_name_plural": "descuentos por médico arrendatario",
                "ordering": (
                    "tenant_doctor__display_name",
                    "-start_date",
                    "-created_at",
                ),
            },
        ),
        migrations.AddField(
            model_name="statement",
            name="applied_tenant_discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statements",
                to="finance.tenantdoctordiscount",
            ),
        ),
    ]
