# Generated by Django 5.2.15 on 2026-10-01 00:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_payment_allocations(apps, schema_editor):
    Payment = apps.get_model("finance", "Payment")
    PaymentAllocation = apps.get_model("finance", "PaymentAllocation")
    payments = Payment.objects.exclude(reservation_id=None).select_related("reservation")
    for payment in payments.iterator():
        payment.batch_id = payment.reservation.batch_id
        payment.save(update_fields=["batch"])
        PaymentAllocation.objects.get_or_create(
            payment_id=payment.pk,
            reservation_id=payment.reservation_id,
            defaults={
                "statement_id": payment.statement_id,
                "amount": payment.amount,
                "created_by_id": payment.created_by_id,
                "updated_by_id": payment.updated_by_id,
            },
        )


def clear_backfilled_batch_links(apps, schema_editor):
    Payment = apps.get_model("finance", "Payment")
    Payment.objects.exclude(reservation_id=None).update(batch_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_statement_room_discount_percentage_and_more'),
        ('scheduling', '0008_alter_reservationbatch_deadline_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_submissions', to='scheduling.reservationbatch', verbose_name='grupo de reservaciones'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='scheduling.reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.statement'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(batch__isnull=False)
                    | models.Q(
                        reservation__isnull=False,
                        statement__isnull=False,
                    )
                ),
                name='finance_payment_requires_subject',
            ),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='importe asignado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.payment', verbose_name='pago')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='scheduling.reservation', verbose_name='reservación')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='finance.statement', verbose_name='estado de cuenta')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asignación de pago',
                'verbose_name_plural': 'asignaciones de pago',
                'ordering': ('reservation__date', 'reservation__start_time', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('payment', 'reservation'), name='finance_payment_allocation_unique_reservation'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_payment_allocation_amount_positive')],
            },
        ),
        migrations.RunPython(
            backfill_payment_allocations,
            clear_backfilled_batch_links,
        ),
    ]
