# Generated by Django 5.2.15 on 2026-10-01 01:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('catalog', '0006_consultingroom_campus_consultingroom_number_and_more'),
        ('finance', '0008_payment_batch_alter_payment_reservation_and_more'),
        ('scheduling', '0008_alter_reservationbatch_deadline_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('depósito', 'Depósito'), ('saldo_favor', 'Saldo a favor'), ('otro', 'Otro')], default='transferencia', max_length=24, verbose_name='método'),
        ),
        migrations.CreateModel(
            name='CancellationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente de resolución'), ('resuelta', 'Resuelta'), ('sin_devolucion', 'Sin devolución')], default='pendiente', max_length=24, verbose_name='estado')),
                ('resolution_method', models.CharField(choices=[('no_aplica', 'No aplica'), ('devolucion_manual', 'Devolución manual'), ('saldo_favor', 'Saldo a favor')], default='no_aplica', max_length=24, verbose_name='forma de resolución')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='moneda')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total pagado')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='penalización')),
                ('refundable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='importe a devolver')),
                ('refund_reference', models.CharField(blank=True, max_length=160, verbose_name='referencia de devolución')),
                ('refund_date', models.DateField(blank=True, null=True, verbose_name='fecha de devolución')),
                ('refund_receipt', models.FileField(blank=True, null=True, upload_to='refund-receipts/', verbose_name='comprobante de devolución')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='solicitada en')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resuelta en')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_cases', to='scheduling.reservationbatch', verbose_name='grupo de reservaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cancellation_cases', to=settings.AUTH_USER_MODEL, verbose_name='gestionada por')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_cancellation_cases', to=settings.AUTH_USER_MODEL, verbose_name='solicitada por')),
                ('tenant_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_cases', to='catalog.tenantdoctorprofile', verbose_name='médico arrendatario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'expediente de cancelación',
                'verbose_name_plural': 'expedientes de cancelación',
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='CancellationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict, verbose_name='snapshot de política')),
                ('days_before', models.PositiveSmallIntegerField(verbose_name='días naturales antes')),
                ('penalty_percentage', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='porcentaje de penalización')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='importe pagado')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='penalización')),
                ('refundable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='importe a devolver')),
                ('cancelled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='cancelada en')),
                ('cancellation_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.cancellationcase', verbose_name='expediente')),
                ('cancellation_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_items', to='billing.cancellationpolicy', verbose_name='política aplicada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_item', to='scheduling.reservation', verbose_name='reservación')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'partida de cancelación',
                'verbose_name_plural': 'partidas de cancelación',
                'ordering': ('reservation__date', 'reservation__start_time'),
            },
        ),
        migrations.CreateModel(
            name='TenantCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='importe original')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='saldo disponible')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='moneda')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('agotado', 'Agotado'), ('cancelado', 'Cancelado')], default='activo', max_length=16, verbose_name='estado')),
                ('cancellation_case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_credit', to='finance.cancellationcase', verbose_name='expediente de cancelación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='catalog.tenantdoctorprofile', verbose_name='médico arrendatario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saldo a favor',
                'verbose_name_plural': 'saldos a favor',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TenantCreditApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='importe aplicado')),
                ('status', models.CharField(choices=[('reservado', 'Reservado'), ('aplicado', 'Aplicado'), ('liberado', 'Liberado')], default='reservado', max_length=16, verbose_name='estado')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='aplicado en')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='liberado en')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='finance.tenantcredit', verbose_name='saldo a favor')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_applications', to='finance.payment', verbose_name='pago')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aplicación de saldo a favor',
                'verbose_name_plural': 'aplicaciones de saldo a favor',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='cancellationcase',
            constraint=models.CheckConstraint(condition=models.Q(('total_paid__gte', 0)), name='finance_cancellation_total_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cancellationcase',
            constraint=models.CheckConstraint(condition=models.Q(('penalty_amount__gte', 0)), name='finance_cancellation_penalty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cancellationcase',
            constraint=models.CheckConstraint(condition=models.Q(('refundable_amount__gte', 0)), name='finance_cancellation_refundable_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cancellationitem',
            constraint=models.CheckConstraint(condition=models.Q(('penalty_percentage__gte', 0), ('penalty_percentage__lte', 100)), name='finance_cancellation_item_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='cancellationitem',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0), ('penalty_amount__gte', 0), ('refundable_amount__gte', 0)), name='finance_cancellation_item_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='tenantcredit',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0)), name='finance_tenant_credit_original_positive'),
        ),
        migrations.AddConstraint(
            model_name='tenantcredit',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_amount__gte', 0)), name='finance_tenant_credit_remaining_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='tenantcreditapplication',
            constraint=models.UniqueConstraint(fields=('credit', 'payment'), name='finance_credit_application_unique_payment'),
        ),
        migrations.AddConstraint(
            model_name='tenantcreditapplication',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_credit_application_amount_positive'),
        ),
    ]
