# Generated by Django 5.2.15 on 2026-10-01 02:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_consultingroom_campus_consultingroom_number_and_more'),
        ('finance', '0009_alter_payment_method_cancellationcase_and_more'),
        ('scheduling', '0008_alter_reservationbatch_deadline_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('party_type', models.CharField(choices=[('propietario', 'Propietario'), ('arrendatario', 'Médico arrendatario')], max_length=16, verbose_name='tipo de titular')),
                ('period_start', models.DateField(verbose_name='inicio del periodo')),
                ('period_end', models.DateField(verbose_name='fin del periodo')),
                ('available_on', models.DateField(verbose_name='disponible desde')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='moneda')),
                ('status', models.CharField(choices=[('emitido', 'Emitido'), ('anulado', 'Anulado')], default='emitido', max_length=16, verbose_name='estado')),
                ('payout_frequency', models.CharField(blank=True, max_length=16, verbose_name='frecuencia de pago')),
                ('rental_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ingresos por arrendamiento')),
                ('reservation_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cargos por reservación')),
                ('commissions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='comisiones')),
                ('owner_net', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='neto del propietario')),
                ('subscription_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='suscripciones')),
                ('direct_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cuotas de pago directo')),
                ('deducted_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cuotas descontadas')),
                ('reservation_payments', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='pagos de reservaciones')),
                ('account_payments_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='pagos de suscripciones y cuotas')),
                ('payouts_made', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='pagos al propietario')),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='saldo por pagar')),
                ('payout_due', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='saldo por entregar')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='emitido en')),
                ('refreshed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='actualizado en')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_statements', to='catalog.ownerprofile', verbose_name='propietario')),
                ('tenant_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_statements', to='catalog.tenantdoctorprofile', verbose_name='médico arrendatario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estado de cuenta por periodo',
                'verbose_name_plural': 'estados de cuenta por periodo',
                'ordering': ('-period_end', 'party_type'),
            },
        ),
        migrations.CreateModel(
            name='AccountPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('suscripcion_propietario', 'Suscripción de propietario'), ('cuota_propietario', 'Cuota de consultorio'), ('suscripcion_arrendatario', 'Suscripción de médico arrendatario')], max_length=32, verbose_name='concepto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='importe')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='moneda')),
                ('method', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('depósito', 'Depósito'), ('saldo_favor', 'Saldo a favor'), ('otro', 'Otro')], default='transferencia', max_length=24, verbose_name='método')),
                ('reference', models.CharField(blank=True, max_length=160, verbose_name='referencia')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de pago')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='account-payment-receipts/', verbose_name='comprobante')),
                ('status', models.CharField(choices=[('registrado', 'Registrado'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='registrado', max_length=24, verbose_name='estado')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validado en')),
                ('rejected_reason', models.TextField(blank=True, verbose_name='motivo de rechazo')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_account_payments', to=settings.AUTH_USER_MODEL)),
                ('account_statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_payments', to='finance.accountstatement', verbose_name='estado de cuenta')),
            ],
            options={
                'verbose_name': 'pago de suscripción o cuota',
                'verbose_name_plural': 'pagos de suscripciones o cuotas',
                'ordering': ('-payment_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AccountStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('line_type', models.CharField(choices=[('ingreso_arrendamiento', 'Ingreso por arrendamiento'), ('comision_plataforma', 'Comisión de plataforma'), ('neto_propietario', 'Neto del propietario'), ('suscripcion_propietario', 'Suscripción de propietario'), ('cuota_directa', 'Cuota de consultorio'), ('cuota_descontada', 'Cuota descontada del pago'), ('pago_propietario', 'Pago realizado por el propietario'), ('pago_al_propietario', 'Pago al propietario'), ('cargo_reservacion', 'Reservación'), ('pago_reservacion', 'Pago de reservación'), ('suscripcion_arrendatario', 'Suscripción de médico arrendatario'), ('pago_suscripcion_arrendatario', 'Pago de suscripción')], max_length=40, verbose_name='tipo de movimiento')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('effective_date', models.DateField(verbose_name='fecha')),
                ('coverage_start', models.DateField(blank=True, null=True, verbose_name='inicio de cobertura')),
                ('coverage_end', models.DateField(blank=True, null=True, verbose_name='fin de cobertura')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='importe')),
                ('source_model', models.CharField(blank=True, max_length=100, verbose_name='modelo origen')),
                ('source_id', models.CharField(blank=True, max_length=64, verbose_name='identificador origen')),
                ('source_snapshot', models.JSONField(blank=True, default=dict, verbose_name='snapshot del origen')),
                ('account_statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.accountstatement', verbose_name='estado de cuenta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_statement_lines', to='scheduling.reservation')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_statement_lines', to='catalog.consultingroom')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_statement_lines', to='finance.settlement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento de estado de cuenta',
                'verbose_name_plural': 'movimientos de estados de cuenta',
                'ordering': ('effective_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='OwnerPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='importe pagado')),
                ('deducted_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cuotas descontadas en el corte')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='moneda')),
                ('reference', models.CharField(max_length=160, verbose_name='referencia')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de pago')),
                ('receipt', models.FileField(upload_to='owner-payout-receipts/', verbose_name='comprobante de transferencia')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('account_statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_payouts', to='finance.accountstatement', verbose_name='estado de cuenta del propietario')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_owner_payouts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pago de corte al propietario',
                'verbose_name_plural': 'pagos de cortes a propietarios',
                'ordering': ('-payment_date', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='accountstatement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', False), ('party_type', 'propietario'), ('tenant_doctor__isnull', True)), models.Q(('owner__isnull', True), ('party_type', 'arrendatario'), ('tenant_doctor__isnull', False)), _connector='OR'), name='finance_account_statement_exact_party'),
        ),
        migrations.AddConstraint(
            model_name='accountstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('owner__isnull', False)), fields=('owner', 'period_start', 'period_end', 'currency'), name='finance_owner_statement_unique_period'),
        ),
        migrations.AddConstraint(
            model_name='accountstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('tenant_doctor__isnull', False)), fields=('tenant_doctor', 'period_start', 'period_end', 'currency'), name='finance_tenant_statement_unique_period'),
        ),
        migrations.AddConstraint(
            model_name='accountpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_account_payment_positive'),
        ),
        migrations.AddConstraint(
            model_name='accountstatementline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='finance_account_statement_line_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='accountstatementline',
            constraint=models.UniqueConstraint(fields=('account_statement', 'line_type', 'source_model', 'source_id'), name='finance_account_line_unique_source'),
        ),
        migrations.AddConstraint(
            model_name='ownerpayout',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_owner_payout_positive'),
        ),
        migrations.AddConstraint(
            model_name='ownerpayout',
            constraint=models.CheckConstraint(condition=models.Q(('deducted_fees__gte', 0)), name='finance_owner_payout_fees_nonnegative'),
        ),
    ]
