# Generated by Django 5.2.15 on 2026-06-30 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_equipment_options_and_more"),
        ("integration", "0001_initial"),
        (
            "scheduling",
            "0003_alter_reservation_options_remove_reservation_end_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("habilitada", "Habilitada"),
                            ("usada", "Usada"),
                            ("revocada", "Revocada"),
                            ("expirada", "Expirada"),
                        ],
                        default="pendiente",
                        max_length=24,
                        verbose_name="estado",
                    ),
                ),
                (
                    "simulated_code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="código simulado"
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="válida desde")),
                ("valid_until", models.DateTimeField(verbose_name="válida hasta")),
                (
                    "enabled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="habilitada en"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="usada en"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revocada en"
                    ),
                ),
                (
                    "expired_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expirada en"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_credentials",
                        to="scheduling.reservation",
                        verbose_name="reservación",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_credentials",
                        to="catalog.consultingroom",
                        verbose_name="consultorio",
                    ),
                ),
                (
                    "tenant_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_credentials",
                        to="catalog.tenantdoctorprofile",
                        verbose_name="médico arrendatario",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "credencial de acceso",
                "verbose_name_plural": "credenciales de acceso",
                "ordering": ("-valid_from", "-created_at"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_deleted", False),
                            ("status__in", ("pendiente", "habilitada", "usada")),
                        ),
                        fields=("reservation",),
                        name="integration_unique_active_access_credential",
                    )
                ],
            },
        ),
    ]
