# Generated by Django 5.2.15 on 2026-06-30 02:43

import apps.identity.managers
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="correo electrónico"
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="nombre")),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="apellidos"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Superadministrador"),
                            ("admin", "Administrador"),
                            ("operator", "Operador"),
                            ("receptionist", "Recepcionista"),
                            ("owner", "Dueño"),
                            ("tenant_doctor", "Médico Arrendatario"),
                            ("auditor", "Auditor"),
                        ],
                        default="tenant_doctor",
                        max_length=32,
                        verbose_name="rol",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("is_staff", models.BooleanField(default=False, verbose_name="staff")),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="fecha de registro",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
                "ordering": ("email",),
            },
            managers=[
                ("objects", apps.identity.managers.CustomUserManager()),
            ],
        ),
    ]
