# Generated by Django 5.2.15 on 2026-07-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_tenantdoctorprofile_assigned_rooms"),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="assigned_clinics",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_users",
                to="catalog.clinic",
                verbose_name="clínicas asignadas",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="assigned_owners",
            field=models.ManyToManyField(
                blank=True,
                related_name="assistant_users",
                to="catalog.ownerprofile",
                verbose_name="propietarios asignados",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="invitation_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="invitación enviada en"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="must_change_password",
            field=models.BooleanField(
                default=False, verbose_name="forzar cambio de contraseña"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="teléfono"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="secondary_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="correo alterno"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="secondary_phone",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="teléfono alterno"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Administrador de sistemas"),
                    ("admin", "Administrador de negocio"),
                    ("operator", "Operador"),
                    ("receptionist", "Recepcionista"),
                    ("owner", "Médico propietario"),
                    ("tenant_doctor", "Médico arrendatario"),
                    ("assistant", "Asistente administrativo"),
                    ("auditor", "Auditor"),
                ],
                default="tenant_doctor",
                max_length=32,
                verbose_name="rol",
            ),
        ),
    ]
