# Generated by Django 5.2.15 on 2026-09-30 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_customuser_assigned_clinics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationScreen",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "key",
                    models.SlugField(max_length=80, unique=True, verbose_name="clave"),
                ),
                ("label", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "url_name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="nombre de ruta"
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=80, verbose_name="icono"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "pantalla",
                "verbose_name_plural": "pantallas",
                "ordering": ("sort_order", "label"),
            },
        ),
        migrations.CreateModel(
            name="RoleScreenPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Administrador de sistemas"),
                            ("admin", "Administrador de negocio"),
                            ("operator", "Operador"),
                            ("receptionist", "Recepcionista"),
                            ("owner", "Médico propietario"),
                            ("tenant_doctor", "Médico arrendatario"),
                            ("assistant", "Asistente administrativo"),
                            ("auditor", "Auditor"),
                        ],
                        max_length=32,
                        verbose_name="rol",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("none", "Sin acceso"),
                            ("read", "Lectura"),
                            ("edit", "Edición"),
                        ],
                        default="none",
                        max_length=12,
                        verbose_name="nivel de acceso",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_permissions",
                        to="identity.applicationscreen",
                        verbose_name="pantalla",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "permiso de pantalla",
                "verbose_name_plural": "permisos de pantalla",
                "ordering": ("screen__sort_order", "role"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("screen", "role"),
                        name="identity_unique_role_screen_permission",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Administrador de sistemas"),
                            ("admin", "Administrador de negocio"),
                            ("operator", "Operador"),
                            ("receptionist", "Recepcionista"),
                            ("owner", "Médico propietario"),
                            ("tenant_doctor", "Médico arrendatario"),
                            ("assistant", "Asistente administrativo"),
                            ("auditor", "Auditor"),
                        ],
                        max_length=32,
                        verbose_name="rol",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "rol asignado",
                "verbose_name_plural": "roles asignados",
                "ordering": ("user__email", "role"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role"),
                        name="identity_unique_user_role_assignment",
                    )
                ],
            },
        ),
    ]
