"""URL routes for commercial configuration."""

from django.urls import path

from apps.billing import views

urlpatterns = [
    path(
        "configuracion/suscripciones-propietarios/",
        views.OwnerSubscriptionListView.as_view(),
        name="owner_subscriptions",
    ),
    path(
        "configuracion/suscripciones-propietarios/nueva/",
        views.OwnerSubscriptionCreateView.as_view(),
        name="owner_subscription_create",
    ),
    path(
        "configuracion/suscripciones-propietarios/<uuid:pk>/activar-desactivar/",
        views.OwnerSubscriptionToggleView.as_view(),
        name="owner_subscription_toggle",
    ),
    path(
        "configuracion/suscripciones-arrendatarios/",
        views.TenantSubscriptionListView.as_view(),
        name="tenant_subscriptions",
    ),
    path(
        "configuracion/suscripciones-arrendatarios/nueva/",
        views.TenantSubscriptionCreateView.as_view(),
        name="tenant_subscription_create",
    ),
    path(
        "configuracion/suscripciones-arrendatarios/<uuid:pk>/activar-desactivar/",
        views.TenantSubscriptionToggleView.as_view(),
        name="tenant_subscription_toggle",
    ),
    path(
        "configuracion/condiciones-propietarios/",
        views.OwnerTermsListView.as_view(),
        name="owner_terms",
    ),
    path(
        "configuracion/condiciones-propietarios/comisiones/nueva/",
        views.OwnerCommissionCreateView.as_view(),
        name="owner_commission_create",
    ),
    path(
        "configuracion/condiciones-propietarios/comisiones/<uuid:pk>/activar-desactivar/",
        views.OwnerCommissionToggleView.as_view(),
        name="owner_commission_toggle",
    ),
    path(
        "configuracion/condiciones-propietarios/pagos/nueva/",
        views.OwnerPayoutCreateView.as_view(),
        name="owner_payout_create",
    ),
    path(
        "configuracion/condiciones-propietarios/pagos/<uuid:pk>/activar-desactivar/",
        views.OwnerPayoutToggleView.as_view(),
        name="owner_payout_toggle",
    ),
    path(
        "configuracion/cuotas-consultorios/",
        views.RoomFeesListView.as_view(),
        name="room_fees",
    ),
    path(
        "configuracion/cuotas-consultorios/fijas/nueva/",
        views.RoomFixedFeeCreateView.as_view(),
        name="room_fixed_fee_create",
    ),
    path(
        "configuracion/cuotas-consultorios/fijas/<uuid:pk>/activar-desactivar/",
        views.RoomFixedFeeToggleView.as_view(),
        name="room_fixed_fee_toggle",
    ),
    path(
        "configuracion/cuotas-consultorios/mensuales/nueva/",
        views.RoomMonthlyFeeCreateView.as_view(),
        name="room_monthly_fee_create",
    ),
    path(
        "configuracion/cuotas-consultorios/mensuales/<uuid:pk>/activar-desactivar/",
        views.RoomMonthlyFeeToggleView.as_view(),
        name="room_monthly_fee_toggle",
    ),
    path(
        "configuracion/politicas-cancelacion/",
        views.CancellationPolicyListView.as_view(),
        name="cancellation_policies",
    ),
    path(
        "configuracion/politicas-cancelacion/nueva/",
        views.CancellationPolicyCreateView.as_view(),
        name="cancellation_policy_create",
    ),
    path(
        "configuracion/politicas-cancelacion/<uuid:pk>/activar-desactivar/",
        views.CancellationPolicyToggleView.as_view(),
        name="cancellation_policy_toggle",
    ),
]
