# Generated by Django 5.2.15 on 2026-06-30 04:07

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_equipment_options_and_more"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availabilityrule",
            options={
                "ordering": ("room__name", "weekday", "start_time"),
                "verbose_name": "regla de disponibilidad",
                "verbose_name_plural": "reglas de disponibilidad",
            },
        ),
        migrations.RemoveField(
            model_name="availabilityrule",
            name="ends_on",
        ),
        migrations.RemoveField(
            model_name="availabilityrule",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="availabilityrule",
            name="starts_on",
        ),
        migrations.AddField(
            model_name="availabilityrule",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="fecha fin"),
        ),
        migrations.AddField(
            model_name="availabilityrule",
            name="end_time",
            field=models.TimeField(
                default=datetime.time(9, 0), verbose_name="hora fin"
            ),
        ),
        migrations.AddField(
            model_name="availabilityrule",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="fecha inicio"
            ),
        ),
        migrations.AddField(
            model_name="availabilityrule",
            name="start_time",
            field=models.TimeField(
                default=datetime.time(8, 0), verbose_name="hora inicio"
            ),
        ),
        migrations.AddField(
            model_name="availabilityrule",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Lunes"),
                    (1, "Martes"),
                    (2, "Miércoles"),
                    (3, "Jueves"),
                    (4, "Viernes"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ],
                default=0,
                verbose_name="día de semana",
            ),
        ),
        migrations.AlterField(
            model_name="availabilityrule",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="availability_rules",
                to="catalog.consultingroom",
            ),
        ),
        migrations.CreateModel(
            name="AvailabilityException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date", models.DateField(verbose_name="fecha")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="hora inicio"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="hora fin"),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("unavailable", "No disponible"),
                            ("maintenance", "Mantenimiento"),
                            ("vacation", "Vacaciones"),
                            ("holiday", "Festivo"),
                            ("other", "Otro"),
                        ],
                        default="unavailable",
                        max_length=32,
                        verbose_name="tipo",
                    ),
                ),
                ("reason", models.CharField(max_length=240, verbose_name="motivo")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="availability_exceptions",
                        to="catalog.consultingroom",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "excepción de disponibilidad",
                "verbose_name_plural": "excepciones de disponibilidad",
                "ordering": ("room__name", "date", "start_time"),
            },
        ),
    ]
