# Generated by Django 5.2.15 on 2026-06-30 05:21

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_alter_availabilityrule_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ("date", "start_time"),
                "verbose_name": "reservación",
                "verbose_name_plural": "reservaciones",
            },
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="end_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="start_at",
        ),
        migrations.AddField(
            model_name="reservation",
            name="cancel_reason",
            field=models.TextField(blank=True, verbose_name="motivo de cancelación"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="cancelada en"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="confirmada en"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="fecha"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="end_time",
            field=models.TimeField(
                default=datetime.time(9, 0), verbose_name="hora fin"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="requested_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="solicitada en"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_time",
            field=models.TimeField(
                default=datetime.time(8, 0), verbose_name="hora inicio"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("solicitada", "Solicitada"),
                    ("pendiente_pago", "Pendiente de pago"),
                    ("pagada", "Pagada"),
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                    ("finalizada", "Finalizada"),
                ],
                default="solicitada",
                max_length=24,
                verbose_name="estado",
            ),
        ),
    ]
