# Generated by Django 5.2.15 on 2026-08-11 22:42

from decimal import Decimal
from django.db import migrations, models


def backfill_reservation_tariffs(apps, schema_editor):
    reservation = apps.get_model("scheduling", "Reservation")
    statement = apps.get_model("finance", "Statement")
    for item in reservation.objects.all().iterator():
        current_statement = (
            statement.objects.filter(reservation_id=item.pk, status="vigente")
            .order_by("-version")
            .first()
        )
        if current_statement is None:
            continue
        reservation.objects.filter(pk=item.pk).update(
            room_discount_percentage=current_statement.room_discount_percentage,
            tenant_discount_percentage=current_statement.tenant_discount_percentage,
            tariff_total=current_statement.tariff_total,
            tariff_final=current_statement.tariff_final,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_statement_room_discount_percentage_and_more"),
        ("scheduling", "0004_availabilityrule_weekdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="room_discount_percentage",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                max_digits=4,
                verbose_name="descuento consultorio %",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="tariff_final",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="tarifa final",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="tariff_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="tarifa total",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="tenant_discount_percentage",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                max_digits=4,
                verbose_name="descuento médico arrendatario %",
            ),
        ),
        migrations.RunPython(
            backfill_reservation_tariffs,
            migrations.RunPython.noop,
        ),
    ]
