# Generated by Django 5.2.15 on 2026-09-30 21:02

import apps.scheduling.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('catalog', '0006_consultingroom_campus_consultingroom_number_and_more'),
        ('scheduling', '0005_reservation_room_discount_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference', models.CharField(default=apps.scheduling.models.generate_reservation_batch_reference, editable=False, max_length=12, unique=True, verbose_name='referencia')),
                ('batch_type', models.CharField(choices=[('single', 'Única'), ('recurring', 'Repetitiva')], default='single', max_length=12, verbose_name='tipo de reservación')),
                ('status', models.CharField(choices=[('requested', 'Por confirmar'), ('confirmed', 'Confirmada'), ('partially_cancelled', 'Cancelada parcialmente'), ('cancelled', 'Cancelada'), ('expired', 'Vencida')], default='requested', max_length=24, verbose_name='estado')),
                ('recurrence_rule', models.JSONField(blank=True, default=dict, verbose_name='regla de recurrencia')),
                ('occurrence_count', models.PositiveSmallIntegerField(default=1, verbose_name='número de ocurrencias')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='moneda')),
                ('tariff_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='tarifa total')),
                ('tariff_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='tarifa final')),
                ('payment_deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha límite de pago')),
                ('deadline_policy', models.CharField(choices=[('pending_configuration', 'Pendiente de configurar'), ('hours_before', 'Horas antes'), ('previous_day', 'Día calendario anterior'), ('exception_hours', 'Excepción: horas antes')], default='pending_configuration', max_length=32, verbose_name='política de vencimiento')),
                ('deadline_policy_snapshot', models.JSONField(blank=True, default=dict, verbose_name='snapshot de política de vencimiento')),
                ('cancellation_policy_snapshot', models.JSONField(blank=True, default=dict, verbose_name='snapshot de política de cancelación')),
                ('cancellation_terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='términos de cancelación aceptados en')),
                ('payment_proof_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='comprobante enviado en')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='vencida en')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='solicitada en')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('cancellation_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_batches', to='billing.cancellationpolicy', verbose_name='política de cancelación aceptada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_batches', to='catalog.consultingroom', verbose_name='consultorio')),
                ('tenant_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_batches', to='catalog.tenantdoctorprofile', verbose_name='médico arrendatario')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grupo de reservaciones',
                'verbose_name_plural': 'grupos de reservaciones',
                'ordering': ('-requested_at', 'reference'),
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='scheduling.reservationbatch', verbose_name='grupo de reservaciones'),
        ),
        migrations.AddConstraint(
            model_name='reservationbatch',
            constraint=models.CheckConstraint(condition=models.Q(('occurrence_count__gte', 1)), name='scheduling_batch_occurrence_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='reservationbatch',
            constraint=models.CheckConstraint(condition=models.Q(('tariff_total__gte', 0)), name='scheduling_batch_tariff_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='reservationbatch',
            constraint=models.CheckConstraint(condition=models.Q(('tariff_final__gte', 0)), name='scheduling_batch_tariff_final_nonnegative'),
        ),
    ]
