# Generated by Django 5.2.15 on 2026-09-30 22:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_consultingroom_campus_consultingroom_number_and_more'),
        ('scheduling', '0007_backfill_reservation_batches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationbatch',
            name='deadline_policy',
            field=models.CharField(choices=[('pending_configuration', 'Pendiente de configurar'), ('hours_before', 'Horas antes'), ('previous_day', 'Día calendario anterior'), ('exception_hours', 'Excepción: horas antes'), ('admin_override', 'Excepción administrativa')], default='pending_configuration', max_length=32, verbose_name='política de vencimiento'),
        ),
        migrations.CreateModel(
            name='PaymentDeadlineException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('exception_type', models.CharField(choices=[('hours_rule', 'Aplicar regla de horas'), ('late_booking', 'Reservación posterior al vencimiento')], default='hours_rule', max_length=24, verbose_name='tipo de excepción')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('previous_deadline_at', models.DateTimeField(verbose_name='vencimiento anterior')),
                ('replacement_deadline_at', models.DateTimeField(verbose_name='nuevo vencimiento')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='aplicada en')),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_payment_deadline_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='autorizado por')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deadline_exception', to='scheduling.reservationbatch', verbose_name='grupo de reservaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'excepción de vencimiento',
                'verbose_name_plural': 'excepciones de vencimiento',
                'ordering': ('-applied_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('replacement_deadline_at__gt', models.F('previous_deadline_at'))), name='scheduling_deadline_exception_extends_deadline')],
            },
        ),
        migrations.CreateModel(
            name='ReservationPaymentPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False, verbose_name='versión')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha inicio de vigencia')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha fin de vigencia')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('hours_before_start', models.PositiveSmallIntegerField(default=4, verbose_name='horas antes del inicio')),
                ('advance_rule_enabled', models.BooleanField(default=True, verbose_name='usar regla del día anterior para reservaciones anticipadas')),
                ('automatic_cancellation', models.BooleanField(default=True, verbose_name='cancelar automáticamente al vencer')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_payment_policies', to='catalog.clinic', verbose_name='clínica')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_payment_policies', to='catalog.consultingroom', verbose_name='consultorio específico')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'política de pago de reservación',
                'verbose_name_plural': 'políticas de pago de reservaciones',
                'ordering': ('clinic__name', 'room__name', '-start_date', '-version'),
                'constraints': [models.UniqueConstraint(fields=('clinic', 'room', 'version'), name='scheduling_payment_policy_unique_version')],
            },
        ),
    ]
