# Generated by Django 5.2.15 on 2026-06-30 02:43

import apps.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=180, verbose_name="título")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("original_pdf", "PDF original"),
                            ("scanned_pdf", "PDF escaneado"),
                            ("other", "Otro"),
                        ],
                        default="original_pdf",
                        max_length=32,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="nombre original"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/", verbose_name="archivo"
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        validators=[apps.core.validators.validate_sha256],
                        verbose_name="SHA-256",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="versión"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadatos"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "documento",
                "verbose_name_plural": "documentos",
                "ordering": ("title", "version"),
            },
        ),
    ]
