# Generated by Django 5.2.15 on 2026-06-30 13:33

import apps.core.validators
import apps.vault.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_equipment_options_and_more"),
        ("finance", "0006_settlement"),
        (
            "scheduling",
            "0003_alter_reservation_options_remove_reservation_end_at_and_more",
        ),
        ("vault", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentasset",
            options={
                "ordering": ("-created_at", "title", "-version"),
                "verbose_name": "documento",
                "verbose_name_plural": "documentos",
            },
        ),
        migrations.RemoveField(
            model_name="documentasset",
            name="kind",
        ),
        migrations.RemoveField(
            model_name="documentasset",
            name="original_filename",
        ),
        migrations.RemoveField(
            model_name="documentasset",
            name="sha256",
        ),
        migrations.AddField(
            model_name="documentasset",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("contrato", "Contrato"),
                    ("ine", "INE"),
                    ("rfc", "RFC"),
                    ("cedula_profesional", "Cédula profesional"),
                    ("comprobante_domicilio", "Comprobante domicilio"),
                    ("comprobante_pago", "Comprobante pago"),
                    ("reglamento", "Reglamento"),
                    ("fotografia", "Fotografía"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=32,
                verbose_name="tipo de documento",
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="mime_type",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="MIME type"
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notas"),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="original_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="nombre original"
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="catalog.ownerprofile",
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="finance.payment",
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="motivo de rechazo"),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="scheduling.reservation",
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="revisado en"
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="catalog.consultingroom",
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="settlement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="finance.settlement",
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="sha256_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                validators=[apps.core.validators.validate_sha256],
                verbose_name="SHA-256",
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="size_bytes",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="tamaño bytes"
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("recibido", "Recibido"),
                    ("en_revision", "En revisión"),
                    ("aprobado", "Aprobado"),
                    ("rechazado", "Rechazado"),
                    ("reemplazado", "Reemplazado"),
                    ("cancelado", "Cancelado"),
                ],
                default="recibido",
                max_length=24,
                verbose_name="estado",
            ),
        ),
        migrations.AddField(
            model_name="documentasset",
            name="tenant_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="catalog.tenantdoctorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="documentasset",
            name="file",
            field=models.FileField(
                upload_to=apps.vault.models.document_upload_path, verbose_name="archivo"
            ),
        ),
    ]
