# Generated by Django 5.2.15 on 2026-08-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0002_alter_documentasset_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentasset",
            name="mime_type",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="tipo MIME"
            ),
        ),
        migrations.AlterField(
            model_name="documentasset",
            name="size_bytes",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="tamaño en bytes"
            ),
        ),
    ]
