# Generated by Django 5.2.15 on 2026-06-30 02:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=180, verbose_name="nombre")),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=220, verbose_name="razón social"
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=80, unique=True, verbose_name="código"),
                ),
                (
                    "timezone",
                    models.CharField(default="America/Mexico_City", max_length=64),
                ),
            ],
            options={
                "verbose_name": "clínica",
                "verbose_name_plural": "clínicas",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ConsultingRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=160, verbose_name="nombre")),
                ("code", models.SlugField(max_length=80, verbose_name="código")),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="capacidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "consultorio",
                "verbose_name_plural": "consultorios",
                "ordering": ("clinic__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=160, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "equipamiento",
                "verbose_name_plural": "equipamiento",
                "ordering": ("room__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="OwnerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "display_name",
                    models.CharField(max_length=180, verbose_name="nombre público"),
                ),
            ],
            options={
                "verbose_name": "propietario",
                "verbose_name_plural": "propietarios",
                "ordering": ("display_name",),
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        max_length=160, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "especialidad",
                "verbose_name_plural": "especialidades",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TenantDoctorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "display_name",
                    models.CharField(max_length=180, verbose_name="nombre público"),
                ),
                (
                    "professional_license",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="cédula profesional"
                    ),
                ),
            ],
            options={
                "verbose_name": "médico arrendatario",
                "verbose_name_plural": "médicos arrendatarios",
                "ordering": ("display_name",),
            },
        ),
    ]
