# Generated by Django 5.2.15 on 2026-06-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "ordering": ("name",),
                "verbose_name": "equipamiento",
                "verbose_name_plural": "equipamiento",
            },
        ),
        migrations.RemoveConstraint(
            model_name="consultingroom",
            name="catalog_room_unique_code_per_clinic",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="code",
        ),
        migrations.RemoveField(
            model_name="clinic",
            name="legal_name",
        ),
        migrations.RemoveField(
            model_name="consultingroom",
            name="code",
        ),
        migrations.RemoveField(
            model_name="consultingroom",
            name="specialties",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="room",
        ),
        migrations.AddField(
            model_name="clinic",
            name="address",
            field=models.TextField(blank=True, verbose_name="dirección"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="correo electrónico"
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="teléfono"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="schedule_text",
            field=models.TextField(blank=True, verbose_name="horario"),
        ),
        migrations.AddField(
            model_name="consultingroom",
            name="allowed_specialties",
            field=models.ManyToManyField(
                blank=True,
                related_name="allowed_consulting_rooms",
                to="catalog.specialty",
            ),
        ),
        migrations.AddField(
            model_name="consultingroom",
            name="description",
            field=models.TextField(blank=True, verbose_name="descripción"),
        ),
        migrations.AddField(
            model_name="consultingroom",
            name="equipment",
            field=models.ManyToManyField(
                blank=True, related_name="consulting_rooms", to="catalog.equipment"
            ),
        ),
        migrations.AddField(
            model_name="consultingroom",
            name="excluded_specialties",
            field=models.ManyToManyField(
                blank=True,
                related_name="excluded_consulting_rooms",
                to="catalog.specialty",
            ),
        ),
        migrations.AddField(
            model_name="consultingroom",
            name="floor",
            field=models.CharField(blank=True, max_length=40, verbose_name="piso"),
        ),
        migrations.AddField(
            model_name="consultingroom",
            name="regulations_text",
            field=models.TextField(blank=True, verbose_name="reglamento"),
        ),
        migrations.AddField(
            model_name="consultingroom",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Disponible"),
                    ("inactive", "Inactivo"),
                    ("maintenance", "Mantenimiento"),
                ],
                default="available",
                max_length=24,
                verbose_name="estado",
            ),
        ),
        migrations.AddField(
            model_name="ownerprofile",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notas"),
        ),
        migrations.AddField(
            model_name="ownerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="teléfono"),
        ),
        migrations.AddField(
            model_name="ownerprofile",
            name="professional_license",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="cédula profesional"
            ),
        ),
        migrations.AddField(
            model_name="ownerprofile",
            name="tax_id",
            field=models.CharField(blank=True, max_length=20, verbose_name="RFC"),
        ),
        migrations.AddField(
            model_name="tenantdoctorprofile",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notas"),
        ),
        migrations.AddField(
            model_name="tenantdoctorprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="teléfono"),
        ),
        migrations.AddField(
            model_name="tenantdoctorprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("authorized", "Autorizado"),
                    ("suspended", "Suspendido"),
                    ("blocked", "Bloqueado"),
                ],
                default="pending",
                max_length=24,
                verbose_name="estado",
            ),
        ),
        migrations.AddField(
            model_name="tenantdoctorprofile",
            name="tax_id",
            field=models.CharField(blank=True, max_length=20, verbose_name="RFC"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=160, unique=True, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="ownerprofile",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=180, verbose_name="nombre público"
            ),
        ),
        migrations.AlterField(
            model_name="tenantdoctorprofile",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=180, verbose_name="nombre público"
            ),
        ),
    ]
