# Generated by Django 5.2.15 on 2026-07-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_clinic_hour_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantdoctorprofile",
            name="assigned_rooms",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_tenant_doctors",
                to="catalog.consultingroom",
                verbose_name="consultorios asignados",
            ),
        ),
    ]
