# Generated by Django 5.2.15 on 2026-08-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_tenantdoctorprofile_assigned_rooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultingroom",
            name="campus",
            field=models.CharField(blank=True, max_length=120, verbose_name="campus"),
        ),
        migrations.AddField(
            model_name="consultingroom",
            name="number",
            field=models.CharField(blank=True, max_length=40, verbose_name="número"),
        ),
        migrations.AddField(
            model_name="consultingroom",
            name="tower",
            field=models.CharField(blank=True, max_length=120, verbose_name="torre"),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="timezone",
            field=models.CharField(
                default="America/Mexico_City",
                max_length=64,
                verbose_name="zona horaria",
            ),
        ),
    ]
